{% set python_min = "3.10" %}
{% set version = "" %}

package:
  name: lintquarto
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lintquarto/lintquarto-{{ version }}.tar.gz
  sha256: 3d54927e5bb06f4a7547180b0ff045cf7ba198b49ac406d122a7a30dc43ba4c4

build:
  entry_points:
    - lintquarto = lintquarto.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit
    - pip
  run:
    - python >={{ python_min }}
    - toml
    - tree_sitter
    - tree-sitter-markdown
    - pyyaml

test:
  imports:
    - lintquarto
  commands:
    - pip check
    - lintquarto --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://lintquarto.github.io/lintquarto/
  summary: Package for running linters, formatters, static type checkers and code analysis tools on python code in quarto (.qmd) files.
  dev_url: https://github.com/lintquarto/lintquarto
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amyheather
